name: Fly Deploy
on:
  push:
    branches:
      - master    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  notify_on_dicords:
    needs: [deploy]
    runs-on: ubuntu-20.04
    steps:
      - name: deploy success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          description: deploy succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            
      - name: deploy failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          description: deploy failed!
          details: not OK
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}