name: Periodic Health Check

on:
  push:
    branches:
      - master

# on:
#   schedule:
#     - cron: '0 12 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://dsdfsf123.com/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: false # Optional, defaults to "false"
          # String representation of cookie attached to health check request.
          # Format: `Name=Value`
          # cookie: "token=asdf1234" # Optional, default is empty
          # Basic auth login password pair.
          # Format: `login:password`
          # basic-auth: "login:password" # Optional, default is empty

      - name: ping success
        if: success()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          description: ping succeeded. OK
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: ping failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          description: ping failed! !!!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}