name: commit contain #skip or not then test notify on discord

on:
  push:
    branches:
      - master

jobs:
  if_not_contain_skip:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"


  contain_skip:
    if: ${{ contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

  notify_on_dicords:
    needs: [if_not_contain_skip, contain_skip]
    runs-on: ubuntu-20.04
    steps:
      - name: if Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          description: deploy succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            
      - name: if Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          description: deploy failed!
          details: not OK
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}