name: commit contain #skip or not then test notify on discord

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  if_not_contain_skip:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"


  contain_skip:
    if: ${{ contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
